// <auto-generated />
using System;
using DotnetYuzuncuYilProjesi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetYuzuncuYilProjesi.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotnetYuzuncuYilProjesi.Core.MusicDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NumberOfLikes")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("MusicDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lyrics = "klasikmüziksöz",
                            NumberOfLikes = 5464654,
                            ReleaseYear = 1996,
                            SongId = 1
                        },
                        new
                        {
                            Id = 2,
                            Lyrics = "cazmüziksöz",
                            NumberOfLikes = 46565,
                            ReleaseYear = 1896,
                            SongId = 2
                        },
                        new
                        {
                            Id = 3,
                            Lyrics = "rockmüziksöz",
                            NumberOfLikes = 98798,
                            ReleaseYear = 1976,
                            SongId = 3
                        },
                        new
                        {
                            Id = 4,
                            Lyrics = "bluesmüziksöz",
                            NumberOfLikes = 1531,
                            ReleaseYear = 1953,
                            SongId = 4
                        });
                });

            modelBuilder.Entity("DotnetYuzuncuYilProjesi.Core.PlayList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlayLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 12, 2, 26, 35, 1, DateTimeKind.Local).AddTicks(8024),
                            PlaylistName = "Classical"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 12, 2, 26, 35, 1, DateTimeKind.Local).AddTicks(8035),
                            PlaylistName = "Jazz"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 12, 2, 26, 35, 1, DateTimeKind.Local).AddTicks(8036),
                            PlaylistName = "Rock"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 12, 2, 26, 35, 1, DateTimeKind.Local).AddTicks(8037),
                            PlaylistName = "Blues"
                        });
                });

            modelBuilder.Entity("DotnetYuzuncuYilProjesi.Core.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayListId")
                        .HasColumnType("int");

                    b.Property<string>("Singer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayListId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 12, 2, 26, 35, 1, DateTimeKind.Local).AddTicks(8154),
                            Duration = "9.30 dakika",
                            PlayListId = 1,
                            Singer = "Vivaldi",
                            SongName = "La Follia"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 12, 2, 26, 35, 1, DateTimeKind.Local).AddTicks(8157),
                            Duration = "2.47 dakika",
                            PlayListId = 2,
                            Singer = "Dean Martin",
                            SongName = "Everybody Loves Somebody"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 12, 2, 26, 35, 1, DateTimeKind.Local).AddTicks(8158),
                            Duration = "4.15 dakika",
                            PlayListId = 3,
                            Singer = "Cheap Trick",
                            SongName = "Surrender"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 12, 2, 26, 35, 1, DateTimeKind.Local).AddTicks(8160),
                            Duration = "2.35 dakika",
                            PlayListId = 4,
                            Singer = "Etta James",
                            SongName = "I'd Rather Go Blind"
                        });
                });

            modelBuilder.Entity("DotnetYuzuncuYilProjesi.Core.MusicDetail", b =>
                {
                    b.HasOne("DotnetYuzuncuYilProjesi.Core.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("DotnetYuzuncuYilProjesi.Core.Song", b =>
                {
                    b.HasOne("DotnetYuzuncuYilProjesi.Core.PlayList", "PlayList")
                        .WithMany("Song")
                        .HasForeignKey("PlayListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayList");
                });

            modelBuilder.Entity("DotnetYuzuncuYilProjesi.Core.PlayList", b =>
                {
                    b.Navigation("Song");
                });
#pragma warning restore 612, 618
        }
    }
}
